version: '3.8'
services: 
  webapp:  # aplicação web vai estar aqui, pode chamar de qualquer coisa, mas to chamando de webapp
    container_name: web
    build:  app
    ports:
      - "5000:5000"
    volumes:
    - ./app:/app
  redis: 
    container_name: redis
    image:  redis:alpine # a aplicação vai se conectar aqui
